appuio/charts

baas-operator/Chart.yaml, baas-operator/templates/clusterrole.yaml
For users to be able to manage the custom resources, new aggregated
cluster roles [1] are created.
[1] https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles
=> Add aggregated cluster roles for users

.ci/build.sh, .travis.yml
The Travis script is enhanced to perform HelmQA checking on the charts. It runs in SaaS mode by default but can also run in Docker mode or be disabled completely. Checks could fail or just warn, right now they always fail.
The code is not yet great, e.g. this could be outsourced into a second script which could ship with HelmQA to be maintained centrally. But it would be good to get some feedback on functionality by chart maintainers to drive the next steps.
=> HelmQA integration

.ci/build.sh, baas-operator/Chart.yaml, keycloak/Chart.yaml, maxscale/Chart.yaml, openshift-oauth-proxy/Chart.yaml, prometheus-blackbox-exporter/Chart.yaml, prometheus/Chart.yaml, secret/Chart.yaml
If a chart was changed without having it's version bumped, fail the
build. In order for this to work, all chart versions were bumped by a
patch version.
=> Test for version bump

stardog/Chart.yaml, stardog/files/stardog.properties
As confirmed by the Stardog support, this workaround is no longer
needed.
=> [Stardog] Remove workaround

.ci/build.sh, keycloak/Chart.yaml, keycloak/README.md, keycloak/requirements.lock, keycloak/requirements.yaml
The one in the stable repo was deprecated in favor of the new one in the
Codecentric repo.
=> [keycloak] Switch to new upstream chart

stardog/Chart.yaml, stardog/templates/statefulset.yaml, stardog/values.yaml
Remove labels from PVC.
Upgrade Stardog.
=> [stardog] Remove PVC label, upgrade

signalilo/Chart.yaml, signalilo/README.md, signalilo/templates/deployment.yaml, signalilo/templates/secret.yaml, signalilo/values.yaml
Signalilo v0.0.2 expects to be configured through environment variables.
This commit refactors the helm chart to provide the required config
through environment variables, from values provided in `.Values.config`
and allows extra configuration values to be provided as environment
variables in `.Values.extraEnvVars`.
Signed-off-by: Simon Gerber <simon.gerber@vshn.ch>
The new version v0.0.2 of Signalilo is configurable via environment variables instead of a config file. This PR refactors the Signalilo chart to provide the configuration via environment variables.
=> [signalilo] Use environment variables for configuration

stardog/Chart.yaml, stardog/templates/statefulset.yaml
Increase liveness probe delay to allow for longer startup time if DBs need to be synced from other
nodes.
=> [stardog] Increase liveness probe delay

.ci/build.sh, k8up/Chart.yaml, k8up/templates/clusterrole.yaml
During the preparation of a K8up workshop it was observed that PreBackupPod objects would not run without this permission. The workaround was to manually run the following command and append the permissions:
`kubectl edit clusterroles k8up`
=> [k8up] Added missing permissions for K8up to run PreBackupPod object

keycloak/Chart.yaml, keycloak/README.md
The upstream chart from Codecentric now includes the OpenShift route.
Therefore there's no need to have our own chart anymore.
=> [Keycloak] Deprecate chart

stardog/Chart.yaml, stardog/templates/post-install-manage-users.yaml, stardog/templates/statefulset.yaml
Stardog implemented a new health check endpoint, specifically for
Kubernetes.
=> [Stardog] Update health check endpoint

stardog/Chart.yaml, stardog/templates/monitoring/stardog-java-rules.yaml, stardog/templates/monitoring/stardog-rules.yaml, stardog/templates/monitoring/zookeeper-rules.yaml
Make sure the deployed PrometheusRules are scoped to the release's
namespace.
=> [Stardog] Limit Promehteus rules to current namespace

k8up/Chart.yaml, k8up/README.md
This PR adds documentation how K8up can be installed when tiller has no cluster-admin rights.
=> [k8up] Document installation without cluster-admin

haproxy/Chart.yaml, haproxy/README.md, haproxy/templates/configmap-galera.yaml, haproxy/templates/configmap-ldap-tls.yaml, haproxy/values.yaml
Adds a configuration to use HAProxy as a proxy for a Galera cluster.
Additonally split up the README to document the specific configurations.
=> [haproxy] Add Galera configuration

haproxy/Chart.yaml, haproxy/templates/configmap-galera.yaml
Fixes the Galera configuration by adding a colon.
=> [haproxy] Add a missing colon between address and port

stardog/Chart.yaml, stardog/templates/statefulset.yaml
Use the `/admin/healthcheck` endpoint for readiness probes as it
reflects the readiness of a Stardog instance. It will succeed only if
the instance joined the cluster.
=> [Stardog] Update readiness probe

stardog/Chart.yaml, stardog/templates/statefulset.yaml
Have the temp data in an emptyDir, instead of in the pod fs.
=> [Stardog] Mount emptyDir for tmp data

openshift-route/Chart.yaml, openshift-route/README.md, openshift-route/values.yaml
Signed-off-by: Chris <github.account@chrigel.net>
Updates the default route to `http`, as that would take the port number of the associated service object.
=> [openshift-route] Update named service port

stardog/Chart.yaml, stardog/templates/statefulset.yaml
The probes have proved to not be reliable, because the endpoints show
increased response times when under heavy load. This leads to restarted
pods because we can't anticipate the load for this application.
=> [stardog] Remove the probes

k8up/Chart.yaml, k8up/values.yaml
I am assuming the v0.1.6 release from November is stable now.
To have the latest version in production.
=> [k8up] upgrade to latest version

stardog/Chart.yaml, stardog/templates/statefulset.yaml
To avoid the situation having a zombie pod we are adding the livenessProbe.
Resolves: SBAR-173
=> [chart] Add livenessProbe to Stardog

.ci/build.sh, snappass/.helmignore, snappass/Chart.yaml, stardog/.helmignore, stardog/Chart.yaml, trifid/.helmignore, trifid/Chart.yaml
We often get PRs from Renovate for Go modules which fail in pipeline since the chart version was not bumped. I do not see a reason why the chart should be shipped with the Go testing files, by ignoring the test in the CI build, the build won't fail in the future, so we can safely merge PRs from Renovate without a Chart version bump.
See e.g. #130
=> Ignore test dirs in packaged helm releases

stardog/Chart.yaml, stardog/templates/monitoring/stardog-rules.yaml, stardog/templates/monitoring/zookeeper-rules.yaml
If not all pods of a StatefulSet are ready, fire an alert. As long as at
least 2 pods are ready it's a warning, otherwise a critical alert.
=> [Stardog] Add alert for not ready pods

openshift-route/Chart.yaml, openshift-route/templates/_helpers.tpl, openshift-route/templates/route.yaml
In a wild goose chase, trying to migrate some helm v2 releases to v3 I stumbled across this error:
```
Comparing release=test-helm3-route, chart=../../appuio/charts/openshift-route
********************
Release was not present in Helm.  Diff will show entire contents as new.
********************
in ./route-test.yaml: failed processing release test-helm3-route: helm3 exited with status 1:
Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Route): missing required field "status" in com.github.openshift.api.route.v1.Route
Error: plugin "diff" exited with error
```
This is not an error from diff (so `apply` doesn't work either). Googling around I found these: 
- …
=> [openshift-route] Apply helm3 workaround for broken OpenShift API spec

k8up/Chart.yaml, k8up/values.yaml
- Even on pretty busy clusters, 2 Gi Memory limit is way too high, causing deployment errors on quota-enabled namespaces. Current memory usage is approx. 10mb per 100 namespaces.
- [Upstream K8s best practices](https://learnk8s.io/production-best-practices) recommend to not specify CPU limits for production usage
=> [k8up] Lower resource defaults

k8up/Chart.yaml, k8up/README.md, k8up/templates/deployment.yaml, k8up/test/deployment_test.go, k8up/test/service_test.go, k8up/values.yaml
It's a currently undocumented feature to modify the timezone, but already used productively
=> [k8up] Add dedicated timezone helm variable

data-cube-curation/Chart.yaml, data-cube-curation/templates/deployment.yaml, data-cube-curation/values.yaml
This updates the data-cube-curation app to a newer version. It also changes the `image.tag` value to use the `Chart.AppVersion` by default.
=> [data-cube-curation] use chart appversion as image tag & update the app

data-cube-curation/Chart.yaml
Updates the data-cube-curation app to the latest version.
App changelogs are here:
- https://github.com/zazuko/data-cube-curation/blob/master/api/CHANGELOG.md#031-2020-06-22
- https://github.com/zazuko/data-cube-curation/blob/master/ui/CHANGELOG.md#040-2020-05-06
=> [data-cube-curation] bump image 0.3.0 -> 0.3.1

stardog/Chart.yaml, stardog/requirements.lock, stardog/templates/post-install-job.yaml, stardog/test/go.sum, stardog/test/postinstall_test.go
Signed-off-by: Carole Hamer <carole.hamer@vshn.ch>
This prevents the postinstall job from running when the chart is installed with replicaCount equal to zero. The postinstall job requires at least one running pod in order to terminate successfully, so setting the replica count to zero via gitops always leads to a fail state without this change.
=> [Stardog] Only run postinstall if replicas > 0

data-cube-curation/Chart.yaml, data-cube-curation/templates/deployment.yaml
This fixes the graph store username environment variable in the data-cube-curation chart. Those variables can be seen here: https://github.com/zazuko/data-cube-curation/blob/cffd73e899d0ac9038963d0e8cf709b0f5352b35/api/lib/services/gitLab/trigger.ts#L31-L33
=> [data-cube-curation] fix graph store variable name

data-cube-curation/Chart.yaml, data-cube-curation/templates/configmap.yaml, data-cube-curation/templates/deployment.yaml, data-cube-curation/values.yaml
This updates the data-cube-curation app to the latest version. It includes (mandatory) OIDC authentication support, so this PR adds the values needed.
=> [data-cube-curation] bump to 0.4.0 & OIDC authentication support

data-cube-curation/Chart.yaml, data-cube-curation/templates/configmap.yaml, data-cube-curation/templates/deployment.yaml, data-cube-curation/values.yaml
It adds the `dataCubeCuration.auth.accessRequest` value that sets the `AUTH_ACCESS_REQUEST` environment variable. This variable is used to redirect the user to a page where the user can request access to the app.
It also bumps the app version to 0.6.1
=> [data-cube-curation] support setting the access request URL

stardog/Chart.yaml, stardog/files/stardog-wrapper.sh, stardog/templates/monitoring/stardog-servicemonitor.yaml, stardog/values.yaml
Signed-off-by: Carole Hamer <carole.hamer@vshn.ch>
Replace the use of the jmx-metrics sidecar with the Stardog 7.3 Prometheus endpoint.
=> WIP: [Stardog] Expose stardog prometheus endpoint in Stardog 7.3.2 ServiceMonitor

stardog/Chart.yaml, stardog/templates/cronjob.yaml
The only way to tell if a given Stardog backup is valid is to try restoring it. This PR adds verification steps to the backup cronjob to do the following after performing a backup:
- Restore the backup with a temporary name
- Confirm that the restored database has the same number of triples as the original database
- Drop the restored database
If the backup can't be restored with the same number of triples, the cronjob fails.
=> [Stardog] Verify backups

haproxy/Chart.yaml, haproxy/README.md, haproxy/templates/configmap-galerak8s.yaml, haproxy/values.yaml
Allow usage of DNS service discorvery in HAProxy: https://www.haproxy.com/de/blog/dns-service-discovery-haproxy/
This adds a new config `galerak8s` which can be used e.g. with Kubernetes headless services.
=> [haproxy] Allow DNS service discovery

haproxy/Chart.yaml, haproxy/templates/deployment.yaml
Add an annotation to the pods in order to trigger a restart if the ConfigMap changes.
=> [HAProxy] Trigger restart on config change

haproxy/Chart.yaml, haproxy/README.md, haproxy/templates/_tplvalues.tpl, haproxy/templates/servicemonitor.yaml, haproxy/values.yaml
Configure metric relabelings on the ServiceMonitor.
As implemented for the Redis chart: https://github.com/bitnami/charts/pull/4942
=> [HAProxy] Allow metric relabelings

haproxy/Chart.yaml, haproxy/templates/configmap-galera.yaml, haproxy/templates/configmap-galerak8s.yaml, haproxy/templates/configmap-ldap-tls.yaml, haproxy/templates/configmap-redisk8s.yaml
Configure TCP/HTTP log respectively. Change log format to be more
container friendly.
=> [HAProxy] Tune Log Config

haproxy/Chart.yaml, haproxy/templates/_helpers.tpl, haproxy/templates/configmap-galera.yaml, haproxy/templates/configmap-galerak8s.yaml, haproxy/templates/configmap-ldap-tls.yaml, haproxy/templates/configmap-redisk8s.yaml, haproxy/templates/deployment.yaml
Make use of the health check endpoint [1] if metrics are enabled. Also
factor out the stats frontend.
[1] https://www.haproxy.com/documentation/hapee/latest/onepage/#4-monitor-uri
=> [HAProxy] Use health check endpoint

metrics-server/Chart.yaml, metrics-server/README.md, metrics-server/values.yaml
* Change image location from k8s.gcr.io/metrics-server-amd64 to
k8s.gcr.io/metrics-server/metrics-server
* Increase the version from v0.3.6 to v0.3.7
* Update the Helm chart apiVersion from v1 to v2
=> Update metrics-server image, version and Helm chart apiVersion

k8up/Chart.yaml, k8up/README.md, k8up/rbac-kustomize/kustomization.yaml, k8up/templates/rbac.yaml, k8up/values.yaml
* Bump [K8up to v1.0.2](https://github.com/vshn/k8up/releases/tag/v1.0.2)
* Updates RBAC rules
=> [k8up] Bump K8up to v1.0.2

k8up/Chart.yaml, k8up/README.md, k8up/values.yaml
This PR updates the default `wrestic` version in k8up to the latest release of today, which fixes some important bugs that improve the overall reliablility of k8up operations.
=> [k8up] Update wrestic to 0.2.3

Makefile
* Fixes the chart-version detector check in PRs.
`git diff --dirstat=files,0 origin/master..HEAD -- appuio` can list more directories like `appuio/haproxy/templates` and `appuio/haproxy`.
Relates to #318
=> Fix chart-version PR check

Makefile, appuio/haproxy/Chart.yaml, appuio/haproxy/README.gotmpl.md, appuio/haproxy/README.md, appuio/haproxy/templates/_helpers.tpl, appuio/haproxy/templates/configmap-galerak8s.yaml, appuio/haproxy/templates/configmap-redisk8s.yaml, appuio/haproxy/templates/deployment.yaml, appuio/haproxy/templates/service.yaml, appuio/haproxy/values.yaml
This commit allows to expose the Galera and Redis metrics via haproxy so
they can be scraped by any prometheus instance.
They are exposed via the haproxy service of type `LoadBalancer`.
For galera the endpoints are:
* <haproxy_service_ip>:/metrics/mariadb-0/metrics
* <haproxy_service_ip>:/metrics/mariadb-1/metrics
* <haproxy_service_ip>:/metrics/mariadb-2/metrics
For redis the endpoints are:
* <haproxy_service_ip>:/metrics/redis-0/metrics
* <haproxy_service_ip>:/metrics/redis-1/metrics
* <haproxy_service_ip>:/metrics/redis-2/metrics
=> [haproxy] Add support to expose backend metrics in haproxy

appuio/k8up/Chart.yaml, appuio/k8up/README.md, appuio/k8up/rbac-kustomize/kustomization.yaml, appuio/k8up/templates/prometheus/prometheusrule.yaml, appuio/k8up/test/prometheus/prometheusrule_test.go, appuio/k8up/values.yaml
This change allows to stop firing the alert quicker if failed jobs are cleaned.
=> [k8up] Add "backup failed" alert based on kube_job_status_failed

appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/templates/monitoring/stardog-rules.yaml
Signed-off-by: Gabriel Saratura <gabriel.saratura@vshn.ch>
Added http checks for stardog. The metrics are exported via blackbox
=> [stardog] Add more stardog monitoring rules

appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/values.yaml
Upgrades Stardog to version 7.7.2, fixing the phantom database problem among other things.
=> [stardog] Upgrade Stardog to 7.7.2

appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/templates/cronjob.yaml
The current tactic of comparing restored triple counts to backed up triple counts has caused problems with phantom databases remaining in Stardog's memory for months, leading to cluster sync problems. We're now also seeing write lock acquisition failures during the backup jobs, especially when long transactions are happening, which makes it less likely to actually get a working backup at all, let alone a restore. Backups on one large database rarely succeed even after running for 22h.
The restore also puts a lot of additional IOPS/CPU load on all nodes that could be better spent serving production workloads. The nodes not only have to restore the backup but also recompute indexes afterwards.
Thirdly, according to Stardog this measure is no longer necessary since the bug causing partial …
=> [stardog] Disable backup restore testing

appuio/k8up/Chart.yaml, appuio/k8up/README.md, appuio/k8up/rbac-kustomize/kustomization.yaml, appuio/k8up/templates/prometheus/prometheusrule.yaml, appuio/k8up/values.yaml
* Updates K8up to [v2.0.1](https://github.com/k8up-io/k8up/releases/tag/v2.0.1) (includes prometheus namespace change for metrics)
=> [k8up] Update K8up to v2.0.1

appuio/redis/Chart.yaml, appuio/redis/README.md, appuio/redis/values.yaml
With Kubernetes v1.20 a bug was fixed where exec probe timeouts were not
respected. This fix led to failing probes for Redis because the timeout
of 1s is actually too short.
=> [redis] Increase probe timeouts

appuio/mariadb-galera/Chart.yaml, appuio/mariadb-galera/README.md, appuio/mariadb-galera/values.yaml
With Kubernetes v1.20 a bug was fixed where exec probe timeouts were not
respected. This fix led to failing probes for Redis because the timeout
of 1s is actually too short.
=> [mariadb-galera] Increase probe timeouts

appuio/stardog/Chart.yaml, appuio/stardog/README.gotmpl.md, appuio/stardog/README.md, appuio/stardog/requirements.lock, appuio/stardog/requirements.yaml, appuio/stardog/templates/configmap.yaml, appuio/stardog/values.yaml
The PR enables configuration of the `spilling.max.file.length` option (see [documentation](https://docs.stardog.com/operating-stardog/server-administration/server-configuration#spillingmaxfilelength)).
This can be necessary to work around an issue where Stardog spills despite having `FINISH_QUERY_EXECUTION` configured as `query.memory.exceeds.strategy`.
As a workaround, Stardog recommends setting `spilling.max.file.length` to 0 to physically prevent spilling for the whole server. By default, this option is set to 10G.
=> Make spilling.max.file.length configurable

appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/templates/monitoring/stardog-rules.yaml
* Alerts may refire when a pod is restarted, causing duplicated alerts
=> [stardog] Deduplicated license expiry alerts

appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/templates/monitoring/stardog-rules.yaml, appuio/stardog/values.yaml
* This upgrades Stardog to upstream version 7.8.1 which addresses CVE-2021-44228 ([release notes](https://docs.stardog.com/release-notes/stardog-platform#781-release-2021-12-10))
* Fixes a YAML syntax error in the monitoring rules introduced in #377
=> [stardog] Upgrade Stardog to 7.8.1

appuio/haproxy/Chart.yaml, appuio/haproxy/README.md, appuio/haproxy/templates/configmap-redisk8s.yaml
After a failover, checks will fail for the former leader node.
Without shutting down open connections after such an event, applications
can, depending on their client-library implementation, get stuck with open
connections to the former leader, which is now a read-only follower.
This in turn leads to read-only errors for write operations, as long as
the application does not initiate a re-connect.
We should not rely on client-libraries initiating re-connects for such
events when we abstract the Sentinel away with HAProxy.
=> [haproxy][redis] Shutdown connections after failed check

appuio/secret/.helmignore, appuio/secret/Chart.yaml, appuio/secret/README.gotmpl.md, appuio/secret/README.md, appuio/secret/templates/NOTES.txt, appuio/secret/templates/_helpers.tpl, appuio/secret/templates/secret-deprecated.yaml, appuio/secret/templates/secret.yaml, appuio/secret/test/main_test.go, appuio/secret/test/secret_array_test.go, appuio/secret/test/secret_object_test.go, appuio/secret/test/testdata/secret-array.yaml, appuio/secret/test/testdata/secret-object.yaml, appuio/secret/values.yaml
* Updates the generic `Secret` chart with a new value usage with additional fields.
* Added upgrade documentation
* Now also supports templated strings via `stringDataTemplates`
* Supports new value syntax (example):
```yaml
secrets:
database: # this is the secret name
nameTemplate: '{{ .Release.Name }}-suffix' # this allows referencing secret names from other charts
stringData:
my-user: example
my-file: |
[section]
config = value
data:
my-key: some-base64-encoded-string
labels:
app: database
annotations:
my-annotation: a string value
stringDataTemplates:
my-template: |
date={{ now }}
my-name: '{{ .Values.secrets.database.name }}'
```
=> New configuration syntax for Secrets

appuio/cloud-portal/Chart.yaml, appuio/cloud-portal/README.md, appuio/cloud-portal/templates/configmap.yaml, appuio/cloud-portal/templates/deployment.yaml, appuio/cloud-portal/values.yaml
* Allows configuring env vars using `portal.env` key, which accepts key-values
* Required for https://github.com/appuio/cloud-portal/pull/53
=> Allow configuring environment variables

appuio/stardog/Chart.yaml, appuio/stardog/README.gotmpl.md, appuio/stardog/README.md, appuio/stardog/templates/configmap.yaml, appuio/stardog/values.yaml
* The ZooKeeper session timeout was previously hardcoded in values.yaml but should be configurable. A higher timeout may be required when a Stardog cluster is under load.
=> [stardog] Make ZooKeeper session timeout configurable

appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/templates/monitoring/stardog-rules.yaml
Prometheus alert for expiring stardog license was fixed.
=> Fix stardog prometheus rule

appuio/haproxy/Chart.yaml, appuio/haproxy/README.md, appuio/haproxy/templates/service.yaml, appuio/haproxy/values.yaml
The port is exposed via dedicated service and not via the main haproxy
service.
=> Add additional parameter to control if metrics port should be exposed

appuio/haproxy/Chart.yaml, appuio/haproxy/README.gotmpl.md, appuio/haproxy/README.md, appuio/haproxy/templates/_helpers.tpl, appuio/haproxy/templates/configmap-galera.yaml, appuio/haproxy/templates/configmap-galerak8s.yaml, appuio/haproxy/templates/service.yaml, appuio/haproxy/values.yaml
* Added metrics support for the `galera` haproxy config
* Change endpoint format:
Instead of exposing the individual pods via the `path` of the url, we
will use the `Host` header and use a subdomains for route to the correct
pod.
=> Overhaul metrics exposure for redis and mariadb

appuio/haproxy/Chart.yaml, appuio/haproxy/README.md, appuio/haproxy/templates/metrics-backend-svc.yaml
* The previous label caused the serviceMonitor to match this service and
cause TargetDown errors on prometheus due to non matching ports
=> Change label for metrics service

appuio/haproxy/Chart.yaml, appuio/haproxy/README.md, appuio/haproxy/templates/configmap-galera.yaml, appuio/haproxy/templates/deployment.yaml
=> Fix wrong variable usage for haproxy galera config

.github/workflows/lint.yml, Makefile, README.gotmpl, README.md, readme.go
* Adds another make target in the `make docs` that generates a Markdown table in the README.
* The table contains a badge with a download counter for the corresponding version, and a link to the README.
=> Generate list of charts and download counter in the README

README.md, appuio/k8up/Chart.yaml, appuio/k8up/README.md, appuio/k8up/rbac-kustomize/kustomization.yaml, appuio/k8up/values.yaml
* Update K8up to v2.1.2 (https://github.com/k8up-io/k8up/releases/tag/v2.1.2)
=> Update K8up to v2.1.2

README.md, appuio/haproxy/Chart.yaml, appuio/haproxy/README.md, appuio/haproxy/templates/_helpers.tpl
Without the check option DNS resolution is only attempted at startup.
When the IP of a backend changes (common in Kubernetes environments),
this results in failing connection attempts. Using the check command
enables DNS resolution during runtime.
=> [HAProxy] Add check option to metrics backends

README.md, appuio/haproxy/Chart.yaml, appuio/haproxy/README.md, appuio/haproxy/templates/_helpers.tpl
Without the `init-addr none` option, haproxy will not start up if the
backend doesn't exist yet (i.e is not resolvable yet, because the pod
doesn't exist yet).
Furthermore setting sane hold times for the resolver ensures, that when
a backend pod is restarted, that haproxy will get the new IP address as
soon as possible.
=> Add correct backend check for the metrics backend

README.md, appuio/haproxy/Chart.yaml, appuio/haproxy/README.md, appuio/haproxy/templates/_helpers.tpl
Without the namespace in the backend address, haproxy can't resolve the
backend pod
=> Add missing namespace to the metrics backend address

README.md, appuio/stardog/Chart.yaml, appuio/stardog/README.gotmpl.md, appuio/stardog/README.md, appuio/stardog/values.yaml
* Allow configuring ZooKeeper's `autopurge.snapRetainCount` and `autopurge.purgeInterval` options
If this option is not set, ZooKeeper will keep writing new snapshots indefinitely until its PV runs full.
=> Configure autopurge for ZooKeeper

README.md, appuio/mariadb-galera/Chart.lock, appuio/mariadb-galera/Chart.yaml, appuio/mariadb-galera/README.md, appuio/redis/Chart.lock, appuio/redis/Chart.yaml, appuio/redis/README.md, appuio/snappass/Chart.yaml, appuio/snappass/Makefile, appuio/snappass/README.md, appuio/snappass/requirements.lock, appuio/snappass/requirements.yaml, appuio/stardog/Chart.yaml, appuio/stardog/Makefile, appuio/stardog/README.md, appuio/stardog/requirements.lock, appuio/stardog/requirements.yaml
Bitnami cleaned up their upstream index.yaml in https://github.com/bitnami/charts/pull/10530 which makes old charts unresolvable.
This is a mid-term fix allowing us to release new chart versions until we have updated and tested all Bitnami chart dependencies.
Fixes #426
=> Pin Bitnami index.yaml to pre-cleanup version

README.md, appuio/haproxy/Chart.yaml, appuio/haproxy/README.md, appuio/haproxy/templates/deployment.yaml
* The sidecarContainers parameter will have a image reference to the
container to be used. In order to parameterize the image (and other
values)  we need to use the tpl function to render the parameters
value.
=> Allow rendering helm values in the sidecarContainers parameter

README.md, appuio/trifid/Chart.yaml, appuio/trifid/README.md, appuio/trifid/templates/deployment.yaml
New readiness and liveness probes to more reliably start Trifid pods.
=> New probe timeouts for Trifid

README.md, appuio/stardog/Chart.yaml, appuio/stardog/Makefile, appuio/stardog/README.gotmpl.md, appuio/stardog/README.md, appuio/stardog/requirements.lock, appuio/stardog/requirements.yaml, appuio/stardog/templates/_helpers.tpl, appuio/stardog/values.yaml
* Upgrades Stardog to 8.1.0
* Upgrades the ZooKeeper dependency to Bitnami's 8.1.2 (app version 3.7.0)
=> Upgrade Stardog to 8.1.0

README.md, appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/values.yaml
* Use default updateStrategy for ZooKeeper from upstream chart
Rolling out with OnDelete fails on the empty `UpdateStrategy.rollingUpdate` hash given by upstream and it doesn't seem to be possible to overwrite it with null. 
=> Switch to default ZooKeeper updateStrategy

README.md, appuio/stardog/Chart.yaml, appuio/stardog/Makefile, appuio/stardog/README.md, appuio/stardog/requirements.lock, appuio/stardog/requirements.yaml
Same issue as #426, Bitnami pruned their index again in https://github.com/bitnami/charts/pull/14024.
=> [stardog] Pin bitnami charts index to version before Zookeeper 8.1.2 got removed

README.md, appuio/haproxy/Chart.yaml, appuio/haproxy/README.gotmpl.md, appuio/haproxy/README.md, appuio/haproxy/templates/_helpers.tpl, appuio/haproxy/values.yaml
With this we can forward a view of the https://github.com/vshn/exporter-filterproxy. Is used to provide the metrics related to the namespace.
=> Add option to expose a filterproxy

README.md, appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/templates/ingress.yaml
* Uses `networking.k8s.io/v1` ingress instead of `extensions/v1beta1`
=> [stardog] Use networking.k8s.io/v1 ingress

README.md, appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/templates/ingress.yaml, appuio/stardog/values.yaml
* Fixes ZooKeeper anti-affinity rules that ensured anti-affinity to Stardog pods
=> [stardog] Fix ZooKeeper anti-affinity rules

README.md, appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/templates/ingress.yaml, appuio/stardog/templates/statefulset.yaml, appuio/stardog/values.yaml
Based off #463
For some reason, `STARDOG_HOME` is defined to be at `/var/lib/stardog/data7`, even though the Stardog version in use is not even 7 anymore.
This commit removes the version number from `STARDOG_HOME`.
This should not be a breaking change.
=> [stardog] Remove (wrong) version from data path

README.md, appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/templates/pdb.yaml
* Only install a PDB when the Stardog replica count is > 1. Otherwise this could prevent nodes from being drained as it refuses to shut down the only pod in a single-replica setup.
* Scope the PDB to a specific instance.
=> Safer PDBs (only for specific instance and replicaCount >1)

CODEOWNERS
=> Remove @anothertobi from CODEOWNERS

README.md, appuio/stardog-userrole-operator/Chart.yaml, appuio/stardog-userrole-operator/README.md, appuio/stardog-userrole-operator/test/deployment_test.go, appuio/stardog-userrole-operator/values.yaml
* Updates Stardog User Role Operator to 0.2.1
=> Update Stardog User Role Operator to 0.2.1

README.md, appuio/stardog-userrole-operator/Chart.yaml, appuio/stardog-userrole-operator/README.md, appuio/stardog-userrole-operator/test/deployment_test.go, appuio/stardog-userrole-operator/values.yaml
* Upgrade Stardog User Role Operator to 0.2.3
=> Upgrade URO to 0.2.3

README.md, appuio/haproxy/Chart.yaml, appuio/haproxy/README.md, appuio/haproxy/templates/_helpers.tpl
We also need the feature introduced in #458 for `galera` not just for `galerak8s`.
This pr simply adds the same config for `galera`.
=> Support exposing a filterproxy for non k8s galera

README.md, appuio/haproxy/Chart.yaml, appuio/haproxy/README.md, appuio/haproxy/templates/_helpers.tpl
The mariadb galera endpoint was not updated with the new metrics enpoints. This PR resolves that.
=> Fix haproxy galera metrics endpoint

README.md, appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/templates/statefulset.yaml
* Terminate Stardog explicitly using a preStop hook
Stardog stopped terminating cleanly starting with version 9 and seemingly only responds to SIGKILL after `terminationGracePeriodSeconds`. This PR copies [an idea](https://github.com/stardog-union/helm-charts/blob/develop/charts/stardog/templates/statefulset.yaml#L156C1-L163C108) from Stardog's developers where they use a preStop hook instead of relying on SIGTERM.
Without this, any upgrade will require a minimum of 10 minutes per instance, likely more since database reindexing can easily take 20 minutes on a data set of half a billion triples.
=> Add preStop hook for cleaner termination of Stardog server

README.md, appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/templates/cronjob.yaml
* Use batch/v1 apiVersion for CronJobs. This means the minimum Kubernetes version for this chart is now 1.21.
=> Use batch/v1 apiVersion for CronJobs

README.md, appuio/haproxy/Chart.yaml, appuio/haproxy/Dockerfile, appuio/haproxy/README.md, appuio/haproxy/files/galera-check.sh, appuio/haproxy/templates/configmap-galera-checkscript.yaml, appuio/haproxy/templates/configmap-galera.yaml, appuio/haproxy/templates/configmap-galerak8s.yaml, appuio/haproxy/templates/deployment.yaml, appuio/haproxy/values.yaml
* This change ensures that Haproxy sends traffic only to nodes with wsred_ready=1 metric set. It queries prometheus endpoint and parses config. Buffer size for haproxy was raised from 16kB to 300kB, otherwise Haproxy can't "see" metrics. 
=> Adding https checks for HAproxy and Galera

README.md, appuio/haproxy/Chart.yaml, appuio/haproxy/README.md, appuio/haproxy/templates/_helpers.tpl
If all backends are down, the haproxy instance should not be served anymore by kubernetes and the readiness probe should fail. Furthermore, we also fail the liveness probe to enforce a restart of haproxy, as this can resolve the issue in some cases (eg. network or dns issues).
=> Adjust health check to return 503 if all backends are down

README.md, appuio/stardog/Chart.yaml, appuio/stardog/README.gotmpl.md, appuio/stardog/README.md, appuio/stardog/templates/monitoring/stardog-servicemonitor.yaml, appuio/stardog/values.yaml
The current interval of 3s is quite idiotic; there is no real value in scraping data every 3 seconds if in the end you're more interested in data over a day or so.
This commit
- removes the value by default, which will cause the scrapeconfig to use the default value configured in Prometheus' global config
- allows us to overwrite the interval and timeouts via values
=> stardog: Unset custom scrape interval

README.md, appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/values.yaml
=> Upgrade Stardog to 10.1.0

README.md, appuio/stardog/Chart.yaml, appuio/stardog/README.md, appuio/stardog/values.yaml
* Prevent `nil pointer exception` when using default values
=> stardog: Fix nil pointer exception with default values
