appuio/charts

- baas-operator/.helmignore
- baas-operator/Chart.yaml
- baas-operator/README.md
- baas-operator/templates/_helpers.tpl
- baas-operator/templates/clusterrole.yaml
- baas-operator/templates/clusterrolebinding.yaml
- baas-operator/templates/deployment.yaml
- baas-operator/templates/serviceaccount.yaml
- baas-operator/values.yaml
This commits adds a first version of the baas (Backup as a Service) operator deployment.
> chart for deploying the baas operator

- baas-operator/Chart.yaml
- baas-operator/templates/clusterrole.yaml
- baas-operator/values.yaml
V0.1.0 of the baas operator brings some significant changes like a new
groupname for the API and new CRDs.
> Changes for version 0.1.0 of the operator

- stardog/Chart.yaml
- stardog/templates/statefulset.yaml
- stardog/values.yaml
Remove workarounds which have beeen fixed in this version. See #7043 [1]
for more details.
[1] https://www.stardog.com/docs/release-notes/#_6_1_3_release_2019_04_03
> Update Stardog to 6.1.3

- exoip/Chart.yaml
- exoip/templates/daemonset.yaml
- exoip/values.yaml
* 4d035fd exoip: remove hostPort configuration
* 4058c0c exoip: Remove probes
> Exoip v1.0.2

- stardog/Chart.yaml
- stardog/templates/cronjob.yaml
- stardog/templates/pull-secret.yaml
- stardog/templates/statefulset.yaml
- stardog/test/statefulset_test.go
The wrong value was referenced for the existing pull secret.
> [stardog] Fix image pull secret

- k8up/Chart.yaml
- k8up/templates/deployment.yaml
- k8up/values.yaml
During a discussion with @srueg we came to the point that this chart should have sane defaults for the resource requests and limits.
> Add resource requests and limits

- prometheus/Chart.yaml
To fix https://github.com/helm/charts/issues/13763
> [prometheus] add apiVersion

- k8up/Chart.yaml
- k8up/README.md
Point to the correct chart repository and improve K8up spelling
> improve README

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> Add contributing guidelines

- signalilo/.helmignore
- signalilo/Chart.yaml
- signalilo/README.md
- signalilo/templates/_helpers.tpl
- signalilo/templates/deployment.yaml
- signalilo/templates/pull-secret.yaml
- signalilo/templates/secret.yaml
- signalilo/templates/service.yaml
- signalilo/values.yaml
> [signalilo] Create Helm chart for Signalilo

- stardog/Chart.yaml
- stardog/requirements.lock
- stardog/requirements.yaml
- stardog/values.yaml
To include various improvements done upstream.
> [stardog] Bump ZooKeeper dependency chart

- stardog/Chart.yaml
- stardog/requirements.lock
- stardog/requirements.yaml
- stardog/values.yaml
Bump Stardog to v6.2.1 and the ZooKeeper dependency.
> [stardog] Bump Stardog and deps

- stardog/Chart.yaml
- stardog/README.md
- stardog/files/jmx-exporter.yaml
- stardog/templates/monitoring/stardog-java-rules.yaml
- stardog/templates/monitoring/stardog-rules.yaml
- stardog/templates/monitoring/stardog-servicemonitor.yaml
- stardog/templates/monitoring/zookeeper-rules.yaml
- stardog/templates/monitoring/zookeeper-servicemonitor.yaml
- stardog/values.yaml
Set up monitoring and alerts using Prometheus operator.
> [stardog] Set up monitoring and alerting

- stardog/Chart.yaml
- stardog/README.md
- stardog/files/jmx-exporter.yaml
- stardog/requirements.lock
- stardog/requirements.yaml
- stardog/templates/monitoring/stardog-java-rules.yaml
- stardog/templates/statefulset.yaml
- stardog/values.yaml
> [stardog] Various improvements

- stardog/Chart.yaml
- stardog/README.md
- stardog/templates/post-install-manage-users.yaml
- stardog/templates/user-pw-secret.yaml
- stardog/values.yaml
> [stardog] Manage stardog users with helm

- signalilo/Chart.yaml
- signalilo/values.yaml
* Upgrade Signalilo to v0.0.3
* Add an example of how to configure a custom Icinga API CA.
> [signalilo] Upgrade to v0.0.3

- stardog/Chart.yaml
- stardog/templates/cronjob.yaml
- stardog/templates/post-install-manage-users.yaml
- stardog/templates/service.yaml
- stardog/templates/statefulset.yaml
> [Stardog] Improve backup & user managing

- signalilo/Chart.yaml
- signalilo/values.yaml
> [Signalilo] Update to 0.1.0

- stardog/Chart.yaml
- stardog/files/jmx-exporter.yaml
- stardog/templates/monitoring/stardog-rules.yaml
- stardog/values.yaml
Upgrade to Stardog 6.2.3 and implement the features added to this release.
> [Stardog] Upgrade to 6.2.3

- stardog/Chart.yaml
- stardog/templates/monitoring/stardog-rules.yaml
A string ending in `}` is no legal JSON element.
> [Stardog] Fix Stardog Prometheus rule

- stardog/Chart.yaml
- stardog/files/log4j2.xml
- stardog/files/stardog.properties
Enable audit log and make sure everything is logged to stdout.
> [Stardog] Update log4j settings

- haproxy/Chart.yaml
- haproxy/templates/configmap-ldap-tls.yaml
> [haproxy] Remove a `}`

- stardog/Chart.yaml
- stardog/templates/monitoring/stardog-servicemonitor.yaml
To prevent missing of short lived connections.
> [Stardog] Increase scrape frequency

- stardog/Chart.yaml
- stardog/templates/monitoring/stardog-servicemonitor.yaml
The timeout can not be higher than the interval.
> [Stardog] Fix scrape interval

- stardog/Chart.yaml
- stardog/README.md
- stardog/requirements.lock
- stardog/requirements.yaml
- stardog/values.yaml
> [Stardog] Upgrade ZooKeeper chart

- stardog/Chart.yaml
- stardog/templates/configmap.yaml
To prevent Stardog nodes from giving up joining the cluster.
> [Stardog] Increase cluster join retry count

- stardog/Chart.yaml
- stardog/templates/post-install-manage-users.yaml
Set GC threds and add more newlines to log output.
> [Stardog] Improve job output

- haproxy/Chart.yaml
- haproxy/README.md
- haproxy/templates/configmap-galera.yaml
- haproxy/values.yaml
Allows TCP checks if mysql checks are not possible/wanted.
> [haproxy] Allow TCP checks and make the mysql check optional

- stardog/Chart.yaml
- stardog/requirements.lock
- stardog/requirements.yaml
- stardog/templates/statefulset.yaml
* Update ZooKeeper to the latest version
* Add readinessProbe back
> [Stardog] Upgrade ZK and add readinessProbe

- signalilo/Chart.yaml
- signalilo/README.md
- signalilo/values.yaml
> [Signalilo] Bump to v0.1.1

- renovate.json
Configure renovate to sign-off commits
> Configure renovate to sign-off commits

- stardog/Chart.yaml
- stardog/README.md
- stardog/files/stardog-wrapper.sh
- stardog/templates/configmap.yaml
- stardog/templates/post-install-job.yaml
- stardog/values.yaml
> [stardog] Add user, role and database support

- openshift-route/Chart.yaml
- openshift-route/README.md
- openshift-route/templates/route.yaml
- openshift-route/values.yaml
> [openshift-route] Add additional labels

- openshift-route/Chart.yaml
- openshift-route/README.md
- openshift-route/templates/route.yaml
> [openshift-route] Fix certificates/key values with multiline strings

- signalilo/Chart.yaml
- signalilo/README.md
- signalilo/values.yaml
> [Signalilo] Upgrade to v0.2.0

- trifid/Chart.yaml
- trifid/README.md
- trifid/templates/deployment.yaml
- trifid/templates/pdb.yaml
- trifid/values.yaml
* Upgrade Trifid to latest
* Make trifid highly available
> [Trifid] High Available

- prometheus/Chart.yaml
- renovate.json
> Config renovate

- .ci/build.sh
- .gitignore
- .travis.yml
- snappass/test/go.mod
- stardog/test/go.mod
- stardog/test/go.sum
- stardog/test/main_test.go
- stardog/test/pull_secret_test.go
- stardog/test/statefulset_test.go
- stardog/test/user_pw_secret_test.go
- trifid/test/go.mod
* Updates Helm repositories based on requirements.yaml
* Runs go test if there is a test dir
> Include helm test in CI pipelines

- .ci/build.sh
Fixes the CI build script, otherwise it fails since the requirements.yml is out of sync with requirements.lock
> Add missing helm dep update

- .ci/build.sh
- snappass/Chart.yaml
Signed-off-by: Simon Rüegg <simon.ruegg@vshn.ch>
> Remove deprecated Helm flag

- renovate.json
- signalilo/Chart.yaml
- signalilo/README.md
- signalilo/values.yaml
> [signalilo] Bump signalilo

- baas-operator/Chart.yaml
Part 1 of Helm's chart deprecation process: https://helm.sh/docs/topics/charts/#deprecating-charts
Use K8up instead
> [baas] Deprecate BaaS chart

- data-cube-curation/.helmignore
- data-cube-curation/Chart.yaml
- data-cube-curation/templates/NOTES.txt
- data-cube-curation/templates/_helpers.tpl
- data-cube-curation/templates/configmap.yaml
- data-cube-curation/templates/deployment.yaml
- data-cube-curation/templates/ingress.yaml
- data-cube-curation/templates/secrets.yaml
- data-cube-curation/templates/service.yaml
- data-cube-curation/templates/tests/test-connection.yaml
- data-cube-curation/values.yaml
I wrote a chart for https://github.com/zazuko/data-cube-curation (see ticket SBAR-178)
It's still kinda WIP (mostly the readme, some missing variables and the registry not being the right one), but I'm waiting on some changes on data-cube-curation to have the UI working correctly.
I chose to split the secrets into multiple ones (with the ability to use an existing one for each one of them), not sure if it's the right way to do it
> data-cube-curation chart

- .ci/build.sh
- snappass/Chart.yaml
- snappass/requirements.lock
- snappass/requirements.yaml
- stardog/Chart.yaml
- stardog/requirements.lock
- stardog/requirements.yaml
Signed-off-by: Soufiane Benali <soufiane.benali@vshn.ch>
> [snappass] Changed snappass redis to bitnami version

- data-cube-curation/Chart.yaml
- data-cube-curation/templates/deployment.yaml
- data-cube-curation/values.yaml
Define image tag in values.yaml
> [datacube] Define image tag in values.yaml

- renovate.json
> Ignore K8s package updates

- stardog/Chart.yaml
This PR upgrades the Stardog version to take advantage of the performance enhancements and other features of 7.3.
> [Stardog] Update to v7.3.2

- stardog/Chart.yaml
- stardog/values.yaml
> [stardog] Upgrade to 7 3 2

- k8up/Chart.yaml
- k8up/templates/clusterrole.yaml
- k8up/templates/clusterrolebinding.yaml
- k8up/values.yaml
Bumping default wrestic to a newer version.
> [k8up] Bump default wrestic version

- .ci/build.sh
Signed-off-by: Carole Hamer <carole.hamer@vshn.ch>
The stable and incubator repositories have moved to a new location. This PR updates the reference accordingly.
See [this announcement](https://helm.sh/blog/new-location-stable-incubator-charts/).
> [all] Update stable chart location

- stardog/Chart.yaml
- stardog/requirements.lock
The bitnami/zookeeper dependency required an update.
> [Stardog] update zookeeper dependency

- stardog/Chart.yaml
- stardog/values.yaml
Signed-off-by: Carole Hamer <carole.hamer@vshn.ch>
This version was provided by Stardog to help prevent the problem of "keys out of order". It has been tested on a copy of the Lindas database and appears not to break it, and this upgrade has gotten an OK from Pierre. However, it should be merged during a maintenance window, just in case.
> [Stardog] Update to v7.4.2

- stardog/Chart.yaml
- stardog/values.yaml
> Revert "[Stardog] Update to v7.4.2"

- stardog/Chart.yaml
- stardog/values.yaml
> Revert "Revert "[Stardog] Update to v7.4.2""

- .ci/build.sh
- haproxy/Chart.yaml
- haproxy/README.md
- haproxy/templates/deployment.yaml
- haproxy/values.yaml
* Update HAProxy to latest version
* Make security context configurable
> [HAProxy] Security Context

- haproxy/Chart.yaml
- haproxy/templates/configmap-galera.yaml
- haproxy/templates/configmap-galerak8s.yaml
- haproxy/templates/configmap-ldap-tls.yaml
- haproxy/templates/configmap-redisk8s.yaml
- haproxy/templates/deployment.yaml
- haproxy/templates/metrics-svc.yaml
Make sure the HAProxy config ends with a newline and remove unnecessary
whitespace.
To fix the following error:
```
parsing [/usr/local/etc/haproxy/haproxy.cfg:52]: Missing LF on last line, file might have been truncated at position 93.
```
> [HAProxy] Fix Config

- haproxy/Chart.yaml
- haproxy/README.md
- haproxy/templates/configmap-galera.yaml
- haproxy/templates/configmap-galerak8s.yaml
- haproxy/templates/deployment.yaml
- haproxy/values.yaml
> [HAProxy] Tune Galera K8s Configuration

- haproxy/Chart.yaml
- haproxy/README.md
- haproxy/templates/pdb.yaml
- haproxy/values.yaml
Signed-off-by: Dominic Gabriel <gabriel@puzzle.ch>
> [haproxy] Add PodDisruptionBudget

- haproxy/Chart.yaml
- haproxy/templates/configmap-galerak8s.yaml
> [HAProxy] Fix Stats

- haproxy/Chart.yaml
- haproxy/README.md
- haproxy/templates/configmap-redisk8s.yaml
- haproxy/values.yaml
> [HAProxy] Configure Redis timeout settings

- stardog-userrole-operator/Chart.yaml
- stardog-userrole-operator/templates/clusterrole.yaml
- stardog-userrole-operator/templates/clusterrolebinding.yaml
> [stardog-userrole-operator] Fix CRB in stardog-userrole-operator

- stardog-userrole-operator/Chart.yaml
- stardog-userrole-operator/crd/stardogrole.yaml
- stardog-userrole-operator/test/deployment_test.go
- stardog-userrole-operator/values.yaml
Signed-off-by: Gabriel Saratura <gabriel.saratura@vshn.ch>
> [stardog-userrole-operator] Bump version stardog userrole operator

- haproxy/Chart.yaml
- haproxy/templates/configmap-galera.yaml
> [HAProxy] Enable DNS resolution for Galera config

- metrics-server/Chart.yaml
- metrics-server/README.md
- metrics-server/ci/ci-values.yaml
- metrics-server/templates/NOTES.txt
- metrics-server/templates/_helpers.tpl
- metrics-server/templates/aggregated-metrics-reader-cluster-role.yaml
- metrics-server/templates/auth-delegator-crb.yaml
- metrics-server/templates/cluster-role.yaml
- metrics-server/templates/metric-server-service.yaml
- metrics-server/templates/metrics-api-service.yaml
- metrics-server/templates/metrics-server-crb.yaml
- metrics-server/templates/metrics-server-deployment.yaml
- metrics-server/templates/metrics-server-serviceaccount.yaml
- metrics-server/templates/pdb.yaml
- metrics-server/templates/psp.yaml
- metrics-server/templates/role-binding.yaml
- metrics-server/templates/tests/test-version.yaml
- metrics-server/values.yaml
The original Helm chart has been deprecated.
> Fork of metrics-server from github.com/helm/charts

- haproxy/Chart.yaml
- haproxy/templates/_helpers.tpl
- haproxy/templates/configmap-galera.yaml
- haproxy/templates/configmap-galerak8s.yaml
- haproxy/templates/configmap-redisk8s.yaml
To increase the retries HAProxy does on a DNS timeout or other failure.
> [HAProxy] Tune resolver config

- haproxy/Chart.yaml
- haproxy/README.md
- haproxy/templates/_helpers.tpl
- haproxy/templates/deployment.yaml
- haproxy/values.yaml
> [HAProxy] Tune livenessProbe & Upgrade

- k8up/Chart.yaml
- k8up/README.md
- k8up/rbac-kustomize/kustomization.yaml
- k8up/values.yaml
> [k8up] Update K8up to v1.0.1

- stardog/Chart.yaml
- stardog/files/log4j2.xml
- stardog/files/stardog-wrapper.sh
- stardog/requirements.lock
- stardog/templates/cronjob.yaml
- stardog/templates/monitoring/stardog-java-rules.yaml
- stardog/templates/monitoring/stardog-rules.yaml
- stardog/templates/monitoring/stardog-servicemonitor.yaml
- stardog/templates/post-install-job.yaml
- stardog/templates/statefulset.yaml
- stardog/test/backup_test.go
- stardog/test/go.sum
- stardog/values.yaml
> [Stardog] Update to version 7

- stardog/Chart.yaml
- stardog/values.yaml
Signed-off-by: Gabriel Saratura <gabriel.saratura@vshn.ch>
Disable zookeeper for prod migration
> Disable zookeper in Stardog

- k8up/Chart.yaml
- k8up/README.md
- k8up/rbac-kustomize/kustomization.yaml
- k8up/values.yaml
* Bumps wrestic to v0.2.2
* Bumps K8up to v1.0.3
> [k8up] Update K8up and Wrestic images

- k8up/Chart.yaml
- k8up/README.md
- k8up/values.yaml
This updates [k8up](https://github.com/vshn/k8up/) to the just released [version `v1.0.4`](https://github.com/vshn/k8up/releases/tag/v1.0.4).
> [k8up] Update of k8up to v1.0.4

- k8up/Chart.yaml
- k8up/Makefile
- k8up/README.md
- k8up/rbac-kustomize/kustomization.yaml
- k8up/values.yaml
> [k8up] Bump K8up to v1.0.5

- stardog/Chart.yaml
- stardog/values.yaml
Signed-off-by: Gabriel Saratura <gabriel.saratura@vshn.ch>
> [startdog] Bump version stardog to 7.6.4

- .github/workflows/release.yml
> Prepare charts before releasing

- appuio/k8up/Chart.yaml
- appuio/k8up/README.md
- appuio/k8up/rbac-kustomize/kustomization.yaml
- appuio/k8up/values.yaml
* Updates K8up to v1.1.0
* Updates wrestic to v0.3.1
* Updates documentation for resources
> [k8up] Update k8up to v1.1.0

- appuio/generic/Chart.yaml
- appuio/generic/README.md
https://github.com/appuio/charts/commit/031e52c8a8bc28cc59131d83ba3c1ea0abe5c718 broke the helm index, let's figure out why
> Dummy chart update to test helm releases CI

- appuio/haproxy/Chart.yaml
- appuio/haproxy/README.md
- appuio/haproxy/templates/_helpers.tpl
> [haproxy] Fix wrong backend in haproxy config

- appuio/k8up/Chart.yaml
- appuio/k8up/README.md
- appuio/k8up/values.yaml
> [k8up] Update wrestic version to v0.3.2

- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
Updates Stardog to the latest available version.
> [stardog] Update Stardog to 7.7.1

- appuio/mariadb-galera/.helmignore
- appuio/mariadb-galera/Chart.yaml
- appuio/mariadb-galera/README.md
- appuio/mariadb-galera/hack/failover-testing/Readme.md
- appuio/mariadb-galera/hack/failover-testing/client.sh
- appuio/mariadb-galera/hack/failover-testing/deny-traffic-to-node.sh
- appuio/mariadb-galera/hack/failover-testing/fill.sql
- appuio/mariadb-galera/hack/failover-testing/monitor.sh
- appuio/mariadb-galera/hack/failover-testing/values.yaml
Adds scripts used for failover/ fissure / upgrade tests.
> [mariadb-galera] Add failover testing scripts

- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
If the values.yaml contains a resource limit, it's NOT possible to unset this via Helm values later on.
> [stardog] Remove default resource limits

- appuio/redis/Chart.yaml
- appuio/redis/README.md
- appuio/redis/values.yaml
Signed-off-by: Fabian Fischer <fabian.fischer@vshn.ch>
> [redis] Fix missplaced forceUpdate key

- appuio/mariadb-galera/Chart.yaml
- appuio/mariadb-galera/README.md
- appuio/mariadb-galera/templates/recreate.yaml
- appuio/mariadb-galera/values.yaml
> [mariadb-galera] Add option to configure pre-upgrade kubectl image

- appuio/redis/Chart.yaml
- appuio/redis/README.md
- appuio/redis/templates/recreate.yaml
- appuio/redis/values.yaml
Signed-off-by: Fabian Fischer <fabian.fischer@vshn.ch>
> [redis] Make image used for pre-upgrade hook configurable

- appuio/signalilo/Chart.yaml
- appuio/signalilo/README.gotmpl.md
- appuio/signalilo/README.md
- appuio/signalilo/templates/deployment.yaml
- appuio/signalilo/values.yaml
PR: https://github.com/appuio/charts/issues/355
Signed-off-by: Iago Santos <iago.santos.pardo@gmail.com>
Add missing extraVolumes and extraVolumeMounts in Signalilo chart
> [Signalilo] Add extraVolumes and extraVolumeMounts for signalilo

- appuio/signalilo/Chart.yaml
- appuio/signalilo/README.md
- appuio/signalilo/templates/deployment.yaml
Signed-off-by: Iago Santos <iago.santos.pardo@adfinis.com>
Fix signalilo templating extraVolumes
> [Signalilo] fix templating extraVolumes

- appuio/mariadb-galera/Chart.yaml
- appuio/mariadb-galera/README.md
- appuio/mariadb-galera/templates/recreate-script.yaml
- appuio/mariadb-galera/templates/recreate.yaml
- appuio/mariadb-galera/values.yaml
> [mariadb-galera] Add script preventing race condition

- appuio/redis/Chart.yaml
- appuio/redis/README.md
- appuio/redis/templates/recreate-script.yaml
- appuio/redis/templates/recreate.yaml
- appuio/redis/values.yaml
Signed-off-by: Fabian Fischer <fabian.fischer@vshn.ch>
> [redis] Add script preventing race condition

- .github/PULL_REQUEST_TEMPLATE.md
- Makefile
- appuio/k8up/Chart.yaml
- appuio/k8up/README.gotmpl.md
- appuio/k8up/README.md
- appuio/k8up/rbac-kustomize/kustomization.yaml
- appuio/k8up/templates/deployment.yaml
- appuio/k8up/templates/prometheus/prometheusrule.yaml
- appuio/k8up/templates/rbac.yaml
- appuio/k8up/test/prometheus/prometheusrule_test.go
- appuio/k8up/values.yaml
* Added Upgrade instructions
* Removed OpenShift 3.11 support
> [k8up] K8up v2 support

- .github/PULL_REQUEST_TEMPLATE.md
- .github/changelog-configuration.json
- .github/changelog.sh
- .github/workflows/changelog.yml
- .github/workflows/release.yml
- .gitignore
- CONTRIBUTING.md
- README.md
- renovate.json
* Adds a changelog generator as inspired by https://github.com/ccremer/charts/releases
* Updates README
> Configure changelog generator

- appuio/cloud-portal/Chart.yaml
- appuio/cloud-portal/README.md
- appuio/cloud-portal/values.yaml
> Upgrade cloud-portal version to `v0.0.2`

- appuio/cloud-portal/Chart.yaml
- appuio/cloud-portal/README.md
- appuio/cloud-portal/values.yaml
* Upgrade cloud-portal to v0.1.0
> Upgrade cloud-portal to v0.1.0

- appuio/haproxy/Chart.yaml
- appuio/haproxy/README.md
- appuio/haproxy/templates/_helpers.tpl
- appuio/haproxy/values.yaml
* Remove deprecated parameter
* Bump version of haproxy
> Remove deprecated parameter and bump haproxy version

- appuio/haproxy/Chart.yaml
- appuio/haproxy/README.md
- appuio/haproxy/templates/service.yaml
> Fix typo in template code

- appuio/haproxy/Chart.yaml
- appuio/haproxy/README.md
- appuio/haproxy/templates/metrics-backend-svc.yaml
> Add missing metrics-backend service

- appuio/haproxy/Chart.yaml
- appuio/haproxy/README.md
- appuio/haproxy/templates/metrics-backend-svc.yaml
> Fix typo in serviceType

- appuio/openshift-route/Chart.yaml
- appuio/openshift-route/README.gotmpl.md
- appuio/openshift-route/README.md
- appuio/openshift-route/values.yaml
* Updates README using helm-docs
> Format Readme with helm-docs

- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
* This PR upgrades the Stardog image used to 7.9.0.
> Upgrade Stardog to 7.9.0

- appuio/cloud-portal/Chart.yaml
- appuio/cloud-portal/README.md
- appuio/cloud-portal/values.yaml
* Bump `cloud-portal` release to `v0.2.0` 
> Bump `cloud-portal` release to `v0.2.0`

- README.md
- appuio/cloud-portal/Chart.yaml
- appuio/cloud-portal/README.md
- appuio/cloud-portal/values.yaml
> Update cloud-portal to v0.2.1

- Makefile
* Updates helm-docs to v1.8.1 https://github.com/norwoodj/helm-docs/releases/tag/v1.8.1
> Update helm-docs to v1.8.1

- README.md
- appuio/haproxy/Chart.yaml
- appuio/haproxy/README.md
- appuio/haproxy/templates/_helpers.tpl
> Fix wrong scope for .Release.Namespace variable

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
* Upgrade Stardog version to 8.0.1
> Bump Stardog to 8.0.1

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
* Fixes ZooKeeper's mismatched updateStrategy configuration (`OnDelete` must not have `spec.updateStrategy.rollingUpdate`)
> Fix ZooKeeper updateStrategy

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/templates/statefulset.yaml
* Refer to the updated secret name for ZooKeeper from upstream
> Refer to updated ZooKeeper secret name

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
> Upgrade Stardog to 8.1.1

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
> Upgrade Stardog to 8.2.1

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
* Upgrades Stardog to 8.2.2, see [release notes](https://github.com/appuio/charts/pull/new/stardog_822)
> Upgrade Stardog to 8.2.2

- README.md
- appuio/snappass/Chart.yaml
- appuio/snappass/README.md
- appuio/snappass/templates/ingress.yaml
* Replace/remove deprecated Ingress api versions.
> Replace/remove deprecated Ingress api versions.

- README.md
- appuio/trifid/Chart.yaml
- appuio/trifid/README.md
- appuio/trifid/templates/pdb.yaml
```
policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```
> [Trifid] Upgrade policy apiVersion

- CODEOWNERS
* Add @ludovicm67  in place of sandhose
> Update codeowners for Trifid etc.

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
> Upgrade Stardog to 9.0.1

- README.md
- appuio/stardog-userrole-operator/Chart.yaml
- appuio/stardog-userrole-operator/README.md
- appuio/stardog-userrole-operator/test/deployment_test.go
- appuio/stardog-userrole-operator/values.yaml
* Upgrade Stardog User Role Operator to 0.2.0
* Adds `DISABLED_ENVIRONMENTS` env variable
> Add disabled environments to uro

- CODEOWNERS
* Adapt CODEOWNERS to reality for Stardog and Stardog User Role Operator
> New code owner for Stardog charts

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
> Upgrade Stardog to 9.1.0

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
> Upgrade Stardog to 9.1.1

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
> Upgrade Stardog to 9.2.0

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
> Upgrade Stardog to 9.2.1

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/templates/monitoring/stardog-rules.yaml
- appuio/stardog/values.yaml
* Adds a helm template to configure the 'for' key of stardog HttpCheck alerts.
> Add template for HttpCheck alert configuration

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/requirements.lock
- appuio/stardog/requirements.yaml
- appuio/stardog/values.yaml
* Upgrade stardog to 10.0.1 and ZooKeeper to 3.8.0
> Stardog 10.0.1

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
> Stardog: Update to Stardog 10.2.0

- CODEOWNERS
> Update charts and code owners for charts used for VSHN offering

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
* Upgrades Chart to use Stardog 10.2.1
> Upgrade Stardog to 10.2.1

- README.md
- appuio/stardog/Chart.yaml
- appuio/stardog/README.md
- appuio/stardog/values.yaml
> Update to Stardog 10.2.2 chart version 0.26.5
